company_name: Флант
company_url: https://flant.ru
site_lang: ru
site_description: Инструмент безопасной доставки вашего кода пользователям.

exclude:
- .gitignore
- Gemfile
- Gemfile.lock
- werf.yaml
- pages_en/

include:
- pages_ru/

breadcrumbs:
  hometext: "Начало"
