name: CLI and API partials checker
on:
  push:
    paths:
      - ".github/workflows/docs_cli_and_api_partials_checker.yml"
      - "client/cmd/**"
      - "server/**"
  workflow_dispatch:

jobs:
  check:
    name: Partials checker
    runs-on: ubuntu-latest
    steps:
      - name: Install werf build dependencies
        run: sudo apt-get install -y libbtrfs-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.18
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare environment
        run: ./e2e/scripts/ci/git.sh

      - name: Regen partials
        run: task docs:gen
