name: Lint
on:
  push:
    paths:
      - '**/*.go'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        directory: [ "client", "server", "e2e" ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install linter
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINARY=golangci-lint bash -s -- v1.38.0

      - name: Lint
        working-directory: ${{ matrix.directory }}
        run: ${GITHUB_WORKSPACE}/bin/golangci-lint run ./... --config ../.golangci.yaml